#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-asukaqlh"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "f03d56d17b274e70bb26e9a673085ba7" }
]

[assets]
directory = "./public"
